### PR TITLE
add dark theme

### LINKED ISSUE #57: [Bug] Dark Mode does not work properly
### Without DarkMode👇
BrightMode

### With DarkMode👇
DarkMode

### I am willing to submit a PR

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/devstream-io/website/issues/57

### CODE REVIEW

**Comment by Arhell** [comment]
cc @daniel-hutao

**Review by daniel-hutao — APPROVED** [review]
LGTM! 👍

**Review by IronCore864 — APPROVED** [review]

**Comment by IronCore864** [comment]
Hi @Arhell, thanks for the contribution, and sorry for the late reply. Great work! Now the dark mode looks much better!

**Comment by aFlyBird0** [comment]
Hi @Arhell , thanks for your contribution! Please [join CNCF's Slack](https://slack.cncf.io/), and join our [channel in CNCF Slack](https://cloud-native.slack.com/messages/devstream)!
Here are a few useful things for you to continue your open-source journey:

If you are searching for something else to work on, please see ["find an issue"](https://docs.devstream.io/en/latest/contributing_guide/#find-an-issue).
Check out our [new contributor guide](https://docs.devstream.io/en/latest/contributing_guide/#new-contributor-guide) and the ["Developer Guide"](https://docs.devstream.io/en/latest/development/development-workflow/).
Read our [blog](https://blog.devstream.io/); they are on [Medium](https://medium.com/devstream), too.

**Comment by aFlyBird0** [comment]
Thank you for contributing! We have issued a Credly badge to you which could be linked to twitter, LinkedIn, etc. Please check your email. (btw, Amazon also use Credly to issue certifications. 😎) @Arhell 

You could find yourself here in the website of devstream: 

https://www.devstream.io/community/community-heroes/opensourcecontributor/associate/

image

**Pull request merged**
